# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from locations import *
import sys



class Ui_NVMe_IP_tool(QtWidgets.QWidget):
    tabs_number = 1
    tabs = []
    SettingsGroupBox = []
    GTLabel = []
    PCIeLabel = []
    GTSelectionComboBox = []
    BlockLocationComboBox = []
    ApplyButton = []
    NVMe_name = []

    def __init__(self):
        super().__init__()
    
    def setupUi(self, NVMe_IP_tool):
        NVMe_IP_tool.setObjectName("NVMe_IP_tool")
        NVMe_IP_tool.resize(700, 390)
        NVMe_IP_tool.setMinimumSize(QtCore.QSize(700, 390))
        NVMe_IP_tool.setMaximumSize(QtCore.QSize(700, 390))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(249, 249, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(249, 249, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(249, 249, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(249, 249, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        NVMe_IP_tool.setPalette(palette)
        NVMe_IP_tool.setDocumentMode(False)
        NVMe_IP_tool.setTabShape(QtWidgets.QTabWidget.Rounded)
        NVMe_IP_tool.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(NVMe_IP_tool)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 341, 211))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 239, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 239, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 239, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 239, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.tabWidget.setPalette(palette)
        self.tabWidget.setObjectName("tabWidget")
        
        for i in range(self.tabs_number):
            self.tabs.append(i)
            self.SettingsGroupBox.append(i)
            self.GTLabel.append(i)
            self.PCIeLabel.append(i)
            self.GTSelectionComboBox.append(i)
            self.BlockLocationComboBox.append(i)
            self.ApplyButton.append(0)

            self.tabs[i] = QtWidgets.QWidget()
            self.tabs[i].setObjectName("tab_" + str(i))
            self.SettingsGroupBox[i] = QtWidgets.QGroupBox(self.tabs[i]) 
            self.SettingsGroupBox[i].setGeometry(QtCore.QRect(10, 10, 311, 131)) 
            font = QtGui.QFont()
            font.setPointSize(10)
            self.SettingsGroupBox[i].setFont(font)
            self.SettingsGroupBox[i].setObjectName("SettingsGroupBox_" + str(i))
            self.GTLabel[i] = QtWidgets.QLabel(self.SettingsGroupBox[i])
            self.GTLabel[i].setGeometry(QtCore.QRect(30, 90, 151, 21))
            font = QtGui.QFont()
            font.setPointSize(10)
            self.GTLabel[i].setFont(font)
            self.GTLabel[i].setObjectName("GTLabel")
            self.PCIeLabel[i] = QtWidgets.QLabel(self.SettingsGroupBox[i])
            self.PCIeLabel[i].setGeometry(QtCore.QRect(30, 40, 151, 21))
            font = QtGui.QFont()
            font.setPointSize(10)
            self.PCIeLabel[i].setFont(font)
            self.PCIeLabel[i].setObjectName("PCIeLabel")
            self.GTSelectionComboBox[i] = QtWidgets.QComboBox(self.SettingsGroupBox[i])
            self.GTSelectionComboBox[i].setGeometry(QtCore.QRect(180, 90, 111, 21))
            self.GTSelectionComboBox[i].setObjectName("GTSelectionComboBox_" + str(i))
            self.BlockLocationComboBox[i] = QtWidgets.QComboBox(self.SettingsGroupBox[i])
            self.BlockLocationComboBox[i].setGeometry(QtCore.QRect(180, 40, 111, 22))
            self.BlockLocationComboBox[i].setObjectName("BlockLocationComboBox")
            self.BlockLocationComboBox[i].addItems(PCIeBlockLocation)
            self.ApplyButton[i] = QtWidgets.QPushButton(self.tabs[i])
            self.ApplyButton[i].setGeometry(QtCore.QRect(220, 150, 81, 30))
            self.ApplyButton[i].setObjectName("ApplyButton")
            self.tabWidget.addTab(self.tabs[i], "")

        self.LogLabel = QtWidgets.QLabel(self.centralwidget)
        self.LogLabel.setGeometry(QtCore.QRect(10, 220, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LogLabel.setFont(font)
        self.LogLabel.setObjectName("LogLabel")
        self.LogWindow = QtWidgets.QListWidget(self.centralwidget)
        self.LogWindow.setGeometry(QtCore.QRect(10, 250, 681, 91))
        self.LogWindow.setObjectName("LogWindow")
        self.ShowSettingsButton = QtWidgets.QPushButton(self.centralwidget)
        self.ShowSettingsButton.setGeometry(QtCore.QRect(360, 180, 131, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ShowSettingsButton.setFont(font)
        self.ShowSettingsButton.setObjectName("ShowSettingsButton")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(360, 0, 331, 131))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.ProjectWindow = QtWidgets.QListWidget(self.groupBox)
        self.ProjectWindow.setGeometry(QtCore.QRect(10, 20, 311, 71))
        self.ProjectWindow.setObjectName("ProjectWindow")
        self.OpenProjectButton = QtWidgets.QPushButton(self.groupBox)
        self.OpenProjectButton.setGeometry(QtCore.QRect(10, 100, 91, 23))
        self.OpenProjectButton.setObjectName("OpenProjectButton")
        NVMe_IP_tool.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(NVMe_IP_tool)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 21))
        self.menubar.setObjectName("menubar")
        NVMe_IP_tool.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(NVMe_IP_tool)
        self.statusbar.setObjectName("statusbar")
        NVMe_IP_tool.setStatusBar(self.statusbar)

        self.retranslateUi(NVMe_IP_tool)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(NVMe_IP_tool)

    def retranslateUi(self, NVMe_IP_tool):
        _translate = QtCore.QCoreApplication.translate
        NVMe_IP_tool.setWindowTitle(_translate("NVMe_IP_tool", "NVMe_IP_editor"))

        for i in range(self.tabs_number):
            
            self.SettingsGroupBox[i].setTitle(_translate("NVMe_IP_tool", self.NVMe_name[i]))
            self.GTLabel[i].setText(_translate("NVMe_IP_tool", "GT Selection"))
            self.PCIeLabel[i].setText(_translate("NVMe_IP_tool", "PCIe Block Location"))
            self.ApplyButton[i].setText(_translate("NVMe_IP_tool", "Apply"))
            self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabs[i]), _translate("NVMe_IP_tool", "NVMe_" + str(i)))
           #self.tabWidget[i].setTabText(self.tabWidget[i].indexOf(self.tabs[i]), _translate("NVMe_IP_tool", "NVMe_" + str(i)))

        
        self.LogLabel.setText(_translate("NVMe_IP_tool", "Log:"))
        self.ShowSettingsButton.setText(_translate("NVMe_IP_tool", "Show IP\'s settings"))
        self.groupBox.setTitle(_translate("NVMe_IP_tool", "Project:"))
        self.OpenProjectButton.setText(_translate("NVMe_IP_tool", "Open Project"))

if __name__ == '__main__':
	app = QtWidgets.QApplication(sys.argv)
	ex = Ui_NVMe_IP_tool()
	ex.setupUi()
	



	sys.exit(app.exec_())
	
