# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys



class Ui_NVMe_IP_tool(object):
    def setupUi(self, NVMe_IP_tool):
        NVMe_IP_tool.setObjectName("NVMe_IP_tool")
        NVMe_IP_tool.resize(700, 390)
        NVMe_IP_tool.setMinimumSize(QtCore.QSize(700, 390))
        NVMe_IP_tool.setMaximumSize(QtCore.QSize(700, 390))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(249, 249, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(249, 249, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(249, 249, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(249, 249, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        NVMe_IP_tool.setPalette(palette)
        NVMe_IP_tool.setDocumentMode(False)
        NVMe_IP_tool.setTabShape(QtWidgets.QTabWidget.Rounded)
        NVMe_IP_tool.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(NVMe_IP_tool)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 341, 211))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 239, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 239, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 239, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 239, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.tabWidget.setPalette(palette)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()##########################################################
        self.tab.setObjectName("tab")##########################################################
        self.SettingsGroupBox = QtWidgets.QGroupBox(self.tab) ##########################################################
        self.SettingsGroupBox.setGeometry(QtCore.QRect(10, 10, 311, 131)) ##########################################################
        font = QtGui.QFont()##########################################################
        font.setPointSize(10)##########################################################
        self.SettingsGroupBox.setFont(font)##########################################################
        self.SettingsGroupBox.setObjectName("SettingsGroupBox")##########################################################
        self.GTLabel = QtWidgets.QLabel(self.SettingsGroupBox)##########################################################
        self.GTLabel.setGeometry(QtCore.QRect(30, 90, 151, 21))##########################################################
        font = QtGui.QFont()##########################################################
        font.setPointSize(10)##########################################################
        self.GTLabel.setFont(font)##########################################################
        self.GTLabel.setObjectName("GTLabel")##########################################################
        self.PCIeLabel = QtWidgets.QLabel(self.SettingsGroupBox)##########################################################
        self.PCIeLabel.setGeometry(QtCore.QRect(30, 40, 151, 21))##########################################################
        font = QtGui.QFont()##########################################################
        font.setPointSize(10)##########################################################
        self.PCIeLabel.setFont(font)##########################################################
        self.PCIeLabel.setObjectName("PCIeLabel")##########################################################
        self.GTSelectionComboBox = QtWidgets.QComboBox(self.SettingsGroupBox)##########################################################
        self.GTSelectionComboBox.setGeometry(QtCore.QRect(180, 90, 111, 21))##########################################################
        self.GTSelectionComboBox.setObjectName("GTSelectionComboBox")##########################################################
        self.BlockLocationComboBox = QtWidgets.QComboBox(self.SettingsGroupBox)##########################################################
        self.BlockLocationComboBox.setGeometry(QtCore.QRect(180, 40, 111, 22))##########################################################
        self.BlockLocationComboBox.setObjectName("BlockLocationComboBox")##########################################################
        self.ApplyButton = QtWidgets.QPushButton(self.tab)##########################################################
        self.ApplyButton.setGeometry(QtCore.QRect(220, 150, 81, 30))##########################################################
        self.ApplyButton.setObjectName("ApplyButton")##########################################################
        self.tabWidget.addTab(self.tab, "")##########################################################
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 10, 321, 131))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_17 = QtWidgets.QLabel(self.groupBox_5)
        self.label_17.setGeometry(QtCore.QRect(30, 90, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.groupBox_5)
        self.label_18.setGeometry(QtCore.QRect(30, 40, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.comboBox_17 = QtWidgets.QComboBox(self.groupBox_5)
        self.comboBox_17.setGeometry(QtCore.QRect(180, 90, 111, 21))
        self.comboBox_17.setObjectName("comboBox_17")
        self.comboBox_18 = QtWidgets.QComboBox(self.groupBox_5)
        self.comboBox_18.setGeometry(QtCore.QRect(180, 40, 111, 22))
        self.comboBox_18.setObjectName("comboBox_18")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_4.setGeometry(QtCore.QRect(220, 150, 81, 30))
        self.pushButton_4.setObjectName("pushButton_4")
        self.tabWidget.addTab(self.tab_2, "")
        self.LogLabel = QtWidgets.QLabel(self.centralwidget)
        self.LogLabel.setGeometry(QtCore.QRect(10, 220, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LogLabel.setFont(font)
        self.LogLabel.setObjectName("LogLabel")
        self.LogWindow = QtWidgets.QTextBrowser(self.centralwidget)
        self.LogWindow.setGeometry(QtCore.QRect(10, 250, 681, 91))
        self.LogWindow.setObjectName("LogWindow")
        self.ShowSettingsButton = QtWidgets.QPushButton(self.centralwidget)
        self.ShowSettingsButton.setGeometry(QtCore.QRect(370, 180, 131, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ShowSettingsButton.setFont(font)
        self.ShowSettingsButton.setObjectName("ShowSettingsButton")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(360, 0, 331, 131))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.ProjectWindow = QtWidgets.QTextBrowser(self.groupBox)
        self.ProjectWindow.setGeometry(QtCore.QRect(10, 20, 311, 71))
        self.ProjectWindow.setObjectName("ProjectWindow")
        self.OpenProjectButton = QtWidgets.QPushButton(self.groupBox)
        self.OpenProjectButton.setGeometry(QtCore.QRect(10, 100, 91, 23))
        self.OpenProjectButton.setObjectName("OpenProjectButton")
        NVMe_IP_tool.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(NVMe_IP_tool)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 21))
        self.menubar.setObjectName("menubar")
        NVMe_IP_tool.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(NVMe_IP_tool)
        self.statusbar.setObjectName("statusbar")
        NVMe_IP_tool.setStatusBar(self.statusbar)

        self.retranslateUi(NVMe_IP_tool)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(NVMe_IP_tool)

    def retranslateUi(self, NVMe_IP_tool):
        _translate = QtCore.QCoreApplication.translate
        NVMe_IP_tool.setWindowTitle(_translate("NVMe_IP_tool", "MainWindow"))
        self.SettingsGroupBox.setTitle(_translate("NVMe_IP_tool", "None"))
        self.GTLabel.setText(_translate("NVMe_IP_tool", "GT Selection"))
        self.PCIeLabel.setText(_translate("NVMe_IP_tool", "PCIe Block Location"))
        self.ApplyButton.setText(_translate("NVMe_IP_tool", "Apply"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("NVMe_IP_tool", "Tab 1"))
        self.groupBox_5.setTitle(_translate("NVMe_IP_tool", "None"))
        self.label_17.setText(_translate("NVMe_IP_tool", "GT Selection"))
        self.label_18.setText(_translate("NVMe_IP_tool", "PCIe Block Location"))
        self.pushButton_4.setText(_translate("NVMe_IP_tool", "Apply"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("NVMe_IP_tool", "Tab 2"))
        self.LogLabel.setText(_translate("NVMe_IP_tool", "Log:"))
        self.ShowSettingsButton.setText(_translate("NVMe_IP_tool", "Show IP\'s settings"))
        self.groupBox.setTitle(_translate("NVMe_IP_tool", "Project:"))
        self.OpenProjectButton.setText(_translate("NVMe_IP_tool", "Open Project"))

if __name__ == '__main__':
	app = QtWidgets.QApplication(sys.argv)
	ex = Ui_NVMe_IP_tool()
	ex.setupUi()
	



	sys.exit(app.exec_())
	
